sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo docker version
  - sudo docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - sudo -E ./build.sh

script:
  - sudo docker images
