sudo: required
dist: trusty

language: go

matrix:
  include:
    - go: 1.4

before_install:
  - sudo apt-get remove -y docker-engine
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo docker version
  - sudo docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - sudo ./build.sh

script:
  - sudo docker images
