sudo: required
dist: trusty

language: go

matrix:
  include:
    - go: 1.4

before_install:
  - apt-get remove -y docker-engine
  - curl -sSL https://get.docker.com/ | sh
  - docker version
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./build.sh

script:
  - docker images
